apiVersion : apps/v1
kind: Deployment
metadata:
  name: spacegameleaderboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spacegameleaderboard
  template:
    metadata:
      labels:
        app: spacegameleaderboard
    spec:
      containers:
        - name: spacegameleaderboard
          image: ghcr.io/canarysplayground/spacegameleaderboard
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: spacegameleaderboard
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: spacegameleaderboard
