apiVersion : apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: ghcr.io/canarysplayground/spacegameweb:${{ steps.date.outputs.date }}.${{ github.run_number }}
          ports:
          - containerPort: 80
