name: Spacegame-Docker

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  leaderboardpush:
    name: Leaderboard Docker Push
    runs-on: ubuntu-latest    
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d')"
        
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Tailspin.SpaceGame.LeaderboardContainer/Dockerfile
          push: true
          tags: |
            ghcr.io/canarysplayground/spacegameleaderboard:latest
            ghcr.io/canarysplayground/spacegameleaderboard:${{ steps.date.outputs.date }}.${{ github.run_number }}
       
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  # spacegamepush:
  #   name: SPACE GAME DOCKER PUSH
  #   runs-on: ubuntu-latest
  #   steps:
      
  #     - name: Checkout
  #       uses: actions/checkout@v2
      
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1
      
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1
        
  #     - name: Login to GitHub Container Registry
  #       uses: docker/login-action@v1
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.repository_owner }}
  #         password: ${{ secrets.CR_PAT }}
          
  #     - name: Get current date
  #       id: date
  #       run: echo "::set-output name=date::$(date +'%Y.%m.%d')"
      
  #     - name: Configure App Settings
  #       uses: cschleiden/replace-tokens@v1
  #       with: 
  #        files: '["Tailspin.SpaceGame.Web/appsettings.json"]'
  #       env:
  #        LEADERBOARD_API_URL: ${{secrets.API_CLUSTER_IP}}

  #     - name: Build and push
  #       id: docker_build
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: .
  #         file: ./Tailspin.SpaceGame.Web/Dockerfile
  #         push: true
  #         tags: |
  #           ghcr.io/canarysplayground/spacegameweb:latest
  #           ghcr.io/canarysplayground/spacegameweb:${{ steps.date.outputs.date }}.${{ github.run_number }}
          
  #     - name: Image digest
  #       run: echo ${{ steps.docker_build.outputs.digest }}
