name: CI 

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  dockerpush:
    name: DOCKER BUILD & PUSH
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Tailspin.SpaceGame.Web/Dockerfile
          push: true
          tags: |
            ${{ github.repository_owner }}/tailspinweb:latest
            ${{ github.repository_owner }}/tailspinweb:1.0.0

