name: SpaceWeb App Service

on:
  push:
    branches: [master]
  release:
    types: [released]

jobs:
  BUILD:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./Tailspin.SpaceGame.Web
      
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./Tailspin.SpaceGame.Web
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: .//Tailspin.SpaceGame.Web
    
    - name: Publish
      run: dotnet publish --no-restore -c Release
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        name: drop
        path: ./Tailspin.SpaceGame.Web/app/publish
    
