name: Tailspin Web CI/CD

on:
  push:
    branches: [ master ]
    paths:
      - .github/workflows/tailspinwebk8s.yml
      - Tailspin.SpaceGame.Web/**
  workflow_dispatch:
  
jobs:
  dockerpush:
    name: DOCKER BUILD & PUSH
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Tailspin.SpaceGame.Web/Dockerfile
          push: true
          tags: |
            ghcr.io/canarysplayground/tailspinweb:latest
            ghcr.io/canarysplayground/tailspinweb:${{ github.run_number }}
       
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
