name: Anchore Container Scan
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  Anchore-Build-Scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
      
    - name: Build taispin-web image
      run: docker build . --file Tailspin.SpaceGame.Web/Dockerfile --tag localbuild/webtestimage:latest
      
    - name: Build tailspin-leaderboards image
      run: docker build . --file Tailspin.SpaceGame.LeaderboardContainer//Dockerfile --tag localbuild/leaderboardstestimage:latest
      
    - name: Anchor Scan Web image
      uses: anchore/scan-action@main
      with:
        image: "localbuild/webtestimage:latest"
        acs-report-enable: true
        
    - name: Anchor Scan Leaderboards image
      uses: anchore/scan-action@main
      with:
        image: "localbuild/leaderboardstestimage:latest"
        acs-report-enable: true 
         
    - name: Upload Anchore Scan Report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif
