name: "Tests"

on:
  push:
    branches: [trunk]
  pull_request:
    branches: [ trunk ]
  workflow_dispatch:

jobs:
  testwebapp:
    name: "Run Tests - WebApp"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
       dotnet-version: 3.1.301 

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./Tailspin.SpaceGame.Web
        
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./Tailspin.SpaceGame.Web
        
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./Tailspin.SpaceGame.Web
  
  testapiapp:
    name: "Run Tests - API"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
          
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./Tailspin.SpaceGame.LeaderboardContainer
        
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./Tailspin.SpaceGame.LeaderboardContainer
        
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./Tailspin.SpaceGame.LeaderboardContainer
