name: TESTS
on:
  pull-request:
    branches: [trunk]
  workflow_dispatch:

jobs:
    test_api_app:
      name: TEST API APP
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
          
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./Tailspin.SpaceGame.LeaderboardContainer
        
      - name: Build
        run: dotnet build --no-restore
        working-directory: ./Tailspin.SpaceGame.LeaderboardContainer

      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: ./Tailspin.SpaceGame.LeaderboardContainer
             
    test_web_app:
      name: TEST WEB APP
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301           
          
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./Tailspin.SpaceGame.Web
        
      - name: Build
        run: dotnet build --no-restore
        working-directory: ./Tailspin.SpaceGame.Web
      
      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: ./Tailspin.SpaceGame.Web
      